<?php 
use Zend\Authentication\AuthenticationService;
echo $this->doctype(); 
?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate(APP_NAME))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon'
            
        ))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')?>
          
			<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>            
			
			
		<!-- Scripts -->
        
        <?php
        
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/noty/packaged/jquery.noty.packaged.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ));
        ?>

</head>

<body >
<?php 
// get service locator
$sl = $this->viewmodel()->getView()->getHelperPluginManager()->getServiceLocator();

$Auth = new AuthenticationService();
// check has identity, else Tests cases will fail
if($Auth->hasIdentity()){
	$AuthStorage = $Auth->getStorage()->read();
	$DirectoryData->buffer();
}

?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?php echo $this->url('home') ?>">&nbsp;<?php echo $this->translate(APP_NAME) ?></a>
			</div>
			<div class="collapse navbar-collapse">
				<?php if($Auth->hasIdentity()){?>
			     <ul class="nav navbar-nav">
					<li class="active"><a href="<?php echo $this->url('user',array('controller'=>'dashboard','action'=>'index')) ?>"><span
							class='glyphicon glyphicon-dashboard'></span> <?php echo $this->translate('Dashboard') ?></a></li>
							
				</ul>
				<?php } else {?>
			     <ul class="nav navbar-nav">
					<li class="active"><a href="<?php //echo $this->url('auth',array('controller'=>'login',)); ?>">
							<?php echo $this->translate('Login') ?></a></li>
					
				</ul>
				<?php }?>
				
				
				<?php if($Auth->hasIdentity()){?>
				<ul class="nav navbar-nav pull-right">

					<li class="dropdown"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-user  "></span> <?php echo $this->translate("Account")?>
							<span class="caret"></span>
					</a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="<?php // echo $this->url('user',array('controller'=>'account','action'=>'profile')) ?>"><span
									class='glyphicon glyphicon-user'></span> <?php echo $this->translate('Profile') ?></a></li>
							<li class="divider"></li>
									
							<li><a href="<?php // echo $this->url('auth',array('controller'=>'login','action'=>'quit')) ?>"><span
									class='glyphicon glyphicon-log-out text text-danger'></span> <?php echo $this->translate('Logout') ?></a></li>
						</ul></li>

				</ul>
				<!--  
				<form class="navbar-form navbar-right"  action="<?php echo $this->url('storage',
				    array('controller'=>'search','action'=>'file'))?>" method='get' role="search">
					<div class="form-group">
						<input type="text" class="form-control input-sm" name='q' placeholder="Search">
					</div>
					<button type="submit" class="btn btn-info btn-sm"><?php echo $this->translate("Go");?></button>
				</form>
				 -->
				<?php }?>
				
			</div>
			<!--/.nav-collapse -->
		</div>
	</nav>
	<div class="container-fluid">
		<div class='row'>
			<div class='col-md-offset-1 col-md-10'>
				<div class='col-md-2'>
                	<div id="directory_tree"></div>				
				</div>
				<div class='col-md-10'>
                    <?php echo $this->partial('flash-messages'); ?>
                    
                    <?php echo $this->layout()->content; ?>
                </div>
			</div>
		</div>
		<div class='row'>
			<div class='col-md-offset-1 col-md-10 '>
				<hr> 
				<footer>
				<br><br>
					<p>&copy; Aspin Management Systems Ltd <?php echo date('Y') ?>. <?php echo $this->translate('All rights reserved.') ?>
					<small class='pull-right'><a href='http://www.bookit24.com'>www.bookit24.com</a></small>
					</p>
					<br><br><br><br><br><br><br><br><br><br>
				</footer>
			</div>
		</div>
	</div>
	<!-- /container -->
    <?php echo $this->inlineScript()?>
    </body>
</html>


<script>
$(function () {
	$('.flash-messages').delay('3000').fadeOut('5000');

});
		
</script>

