<!-- BEGIN PAGE HEAD -->
<div class="page-head">
	<div class="container">
		<!-- BEGIN PAGE TITLE -->
		<div class="page-title">
			<h3>
				Signup
				<hr>
			</h3>
		</div>
		<!-- END PAGE TITLE -->
	</div>
</div>
<!-- END PAGE HEAD -->
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
	<div class="container">
		<!-- BEGIN PAGE CONTENT INNER -->
		<div class="row">

			<div class="col-md-12">
				This is blank page, check file : <br>
				<div class="">
					<code><?php echo __FILE__?></code>
				</div>
			</div>
		</div>
	</div>
</div>